version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    networks:
      - devnet
    depends_on:
      - redis
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - devnet
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - devnet
volumes:
  postgres-data:
networks:
  devnet:
    driver: bridge
